### ISSUE TITLE
Lua as submodule should be pointing at 5.4 and not the master branch

### ISSUE THREAD

**Issue by Pivetta** [georgik/esp-idf-component-lua#1]
Nice you put this on the esp-registry
I just want to point out that the main branch of lua is the developement branch (possibly not stable)

**Comment by georgik** [comment]
@Pivetta Thank you for the suggestion. Yes, that really makes more sense.

It might be reasonable to plug-in also build with tests to validate that specific version of Lua is working correctly.

@kumekay Do you happen to have any recommendation on GitHub Workflow for a component which has multiple versions in upstream repo?

**Comment by kumekay** [comment]
@georgik Could you please explain an example a bit more? As I see, the upstream repo uses git tags

**Comment by georgik** [comment]
@Pivetta Please check new uploads: https://components.espressif.com/components/georgik/lua/
Changes:
- uploaded version 5.4.7 and 5.3.6 which are the most common in projects
- added warning to README of 5.5.0 component, that it's version from the master
